<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="7" total="8" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="111142" started-at="2021-02-04T17:37:38 IST" finished-at="2021-02-04T17:39:29 IST">
    <groups>
      <group name="Regression">
        <method signature="TestVeriday.loginTest()[pri:0, instance:test.TestVeriday@6f46426d]" name="loginTest" class="test.TestVeriday"/>
      </group> <!-- Regression -->
    </groups>
    <test name="TestCRM" duration-ms="111142" started-at="2021-02-04T17:37:38 IST" finished-at="2021-02-04T17:39:29 IST">
      <class name="test.TestVeriday">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:test.TestVeriday@6f46426d]" name="setExtent" is-config="true" duration-ms="84" started-at="2021-02-04T17:37:38 IST" finished-at="2021-02-04T17:37:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="initializeTestBaseSetup(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.TestVeriday@6f46426d]" name="initializeTestBaseSetup" is-config="true" duration-ms="14730" started-at="2021-02-04T17:37:38 IST" finished-at="2021-02-04T17:37:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://node-1.nginx.portal.da-1.demo.qa.aws.veriday.net/login]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[log4j.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:test.TestVeriday@6f46426d]" name="loginTest" duration-ms="67214" started-at="2021-02-04T17:37:53 IST" description="verifying user is able to login page" finished-at="2021-02-04T17:39:00 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pages.LoginPage.LoginToCRM(LoginPage.java:65)
at test.TestVeriday.loginTest(TestVeriday.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:test.TestVeriday@6f46426d]" name="tearDown" is-config="true" duration-ms="21360" started-at="2021-02-04T17:39:00 IST" finished-at="2021-02-04T17:39:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=TestVeriday.loginTest()[pri:0, instance:test.TestVeriday@6f46426d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:test.TestVeriday@6f46426d]" name="endReport" is-config="true" duration-ms="7414" started-at="2021-02-04T17:39:22 IST" finished-at="2021-02-04T17:39:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- test.TestVeriday -->
    </test> <!-- TestCRM -->
  </suite> <!-- Suite -->
</testng-results>
